### ISSUE TITLE
 rofi-window shows up and one can type chars into it, but nothing else happens

### ISSUE THREAD

**Issue by rtng** [gmagno/rofi-ddgr#1]
**OS: Debian GNU/Linux 11 (bullseye) x86_64
Kernel: 5.10.0-20-amd64
WM: IceWM 2.1.2 (Linux/x86_64)
rofi Version: 1.5.4
ddgr Version: 1.9
Python 3.9.2**

**1) running '$rofi -lines 5 -eh 3 -show ddgrsearch -modi "ddgrsearch:ddgr_search.sh" ' prompts  (german):**
+ /usr/local/bin/ddgr_search.sh: Zeile 28: [: : Ganzzahliger Ausdruck erwartet.
+ /usr/local/bin/ddgr_search.sh: Zeile 33: [: : Ganzzahliger Ausdruck erwartet.

**_in english that might be:_**
+ /usr/local/bin/ddgr_search.sh: Line 28: [: : Expected integer expression.
+ /usr/local/bin/ddgr_search.sh: Line 33: [: : Expected integer expression.

**with running this the rofi-window shows up and one can type chars into it, but nothing else happens.**

**2) running '$bash -x ddgr_search.sh' prompts:**
+ echo -en '\0prompt\x1fddgr\n'
promptddgr
+ echo -en '\0delim\x1f;'
delim;+ '[' '' -eq 1 ']'
ddgr_search.sh: Zeile 28: [: : Ganzzahliger Ausdruck erwartet.
+ '[' '' -eq 2 ']'
ddgr_search.sh: Zeile 33: [: : Ganzzahliger Ausdruck erwartet.

**Comment by gmagno** [comment]
Thanks for raising the issue.

Replacing, in `ddgr_search.sh`, the test expressions with double brackets `if [[ ... ]]` test should fix the issue. I will create the PR shortly.
